### PR TITLE
Reproduce of issue #111

### PR DESCRIPTION
**Pull request by ChrisTorng**
Run SignalRSimpleChat, open http://localhost:5001/subpath/ with F12, no error log in Console output. Open http://localhost:5000/subpath/ with F12, Console output shows WebSockets fail, fallback to LongPooling. Uncomment the change in WebSocketProxyMiddleware.cs fixes.

### CODE REVIEW

**Comment by ChrisTorng** [comment]
Sorry, I don't know why it has conflicts and how to resolve. Those conflicts are all my modifications and should be kept.

**Comment by damianh** [comment]
Ok will take it from here, ty.

**Comment by damianh** [comment]
@ChrisTorng 

> Uncomment the change in WebSocketProxyMiddleware.cs fixes.

I've reproduced this locally. Going to add some tests around this....

**Comment by damianh** [comment]
Merged your work and fix via https://github.com/damianh/ProxyKit/commit/2fb417f41c067ba0da88a56682d96eebe8376f08

Thank you taking the time to do the repro.

**Comment by damianh** [comment]
Package should be available at https://www.nuget.org/packages/ProxyKit/2.1.0-beta.2 shortly. If you could take it for a spin and let me know how it goes, then I'll release shortly after.

**Comment by ChrisTorng** [comment]
Sorry, I can't check it until Thursday. Then I'll check and report.

**Comment by damianh** [comment]
No worries.

**Comment by ChrisTorng** [comment]
I've update to beta 2 and have no problem. But actually my project had been changed to use root directory, not `/subpath` anymore, so I'm not checking it on the reported issue's scenario. But I believe it should be OK, because you use exactly my suggested way to fix it. But in fact, I don't think the `TrimStart('/')` is the best way to fix this issue, and have no other better idea. Should you raise `Exception` when calling `ForwardTo` without trailing back slash, especially when it has `/subpath`?

**Comment by damianh** [comment]
Considered the exception / bett-pit-of-success but am happy to get this version out with this approach. I've spotted and edge case regarding trailing slashes #121 and there is an issue with with `.MapWhen()` #66 that ultimately means I need to do my own url matching which will be a breaking change. So I will address this more completely in a future release.

**Pull request closed without merging**
